export const RequestInstance = {
  "data":{
     "requestInstance":{
        "id":"8119884e-c0d3-464d-8a5a-69fdc395ec04",
        "datasetId":"97210",
        "prompts":[
           {
              "id":"MRKT",
              "label":"Markets",
              "type":"MRKT",
              "minSelections":1,
              "maxSelections":0
           },
           {
              "id":"PRDC",
              "label":"Products",
              "type":"PRDC",
              "minSelections":1,
              "maxSelections":0
           },
           {
              "id":"FCT",
              "label":"Facts",
              "type":"FCT",
              "minSelections":1,
              "maxSelections":0
           },
           {
              "id":"PRD",
              "label":"Periods",
              "type":"PRD",
              "minSelections":1,
              "maxSelections":0
           },
           {
              "id":"STR",
              "label":"Stores",
              "type":"STR",
              "minSelections":1,
              "maxSelections":0
           },
           {
              "id":"STR_FCT",
              "label":"Store Facts",
              "type":"FCT",
              "minSelections":1,
              "maxSelections":0
           }
        ],
        "dimensionSelections":[
           {
              "id":"MRKT",
              "virtualDim":false,
              "hidden":false,
              "children":[
                 {
                    "id":"GRP",
                    "label":"Group",
                    "type":"VIEW",
                    "valid":true,
                    "baseUuid":"100",
                    "children":[
                       {
                          "id":"1",
                          "label":"Group1",
                          "type":"GROUP",
                          "valid":true,
                          "pathInfo":[
                             "Group"
                          ],
                          "pathInfoIds":[
                             "GRP"
                          ],
                          "pathInfoTypes":[
                             "VIEW"
                          ],
                          "baseUuid":"91",
                          "children":[
                             {
                                "id":"10001",
                                "label":"Total US",
                                "type":"GROUP_LEVEL",
                                "valid":true,
                                "pathInfo":[
                                   "Group",
                                   "Group1"
                                ],
                                "pathInfoIds":[
                                   "GRP",
                                   "1"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "GROUP"
                                ],
                                "baseUuid":"101",
                                "children":[
                                   {
                                      "id":"21713",
                                      "label":"Total US Drug",
                                      "type":"GROUP_LEVEL_ITEM",
                                      "valid":true,
                                      "pathInfo":[
                                         "Group",
                                         "Total US"
                                      ],
                                      "pathInfoIds":[
                                         "GRP",
                                         "10001"
                                      ],
                                      "pathInfoTypes":[
                                         "VIEW",
                                         "GROUP"
                                      ],
                                      "baseUuid":"102",
                                      "leaf":true
                                   },
                                   {
                                      "id":"22101",
                                      "label":"Total US Food",
                                      "type":"GROUP_LEVEL_ITEM",
                                      "valid":true,
                                      "pathInfo":[
                                         "Group",
                                         "Total US"
                                      ],
                                      "pathInfoIds":[
                                         "GRP",
                                         "10001"
                                      ],
                                      "pathInfoTypes":[
                                         "VIEW",
                                         "GROUP"
                                      ],
                                      "baseUuid":"103",
                                      "leaf":true
                                   },
                                   {
                                      "id":"22105",
                                      "label":"Total US xAOC",
                                      "type":"GROUP_LEVEL_ITEM",
                                      "valid":true,
                                      "pathInfo":[
                                         "Group",
                                         "Total US"
                                      ],
                                      "pathInfoIds":[
                                         "GRP",
                                         "10001"
                                      ],
                                      "pathInfoTypes":[
                                         "VIEW",
                                         "GROUP"
                                      ],
                                      "baseUuid":"104",
                                      "leaf":true
                                   }
                                ],
                                "leaf":false
                             }
                          ],
                          "leaf":false
                       }
                    ],
                    "leaf":false
                 }
              ],
              "accessType":"marketLevelReport"
           },
           {
              "id":"PRD",
              "virtualDim":false,
              "hidden":false,
              "children":[
                 {
                    "id":"GRP",
                    "label":"Group",
                    "type":"VIEW",
                    "valid":true,
                    "baseUuid":"200",
                    "children":[
                       {
                          "id":"7944",
                          "label":"Years",
                          "type":"GROUP_LEVEL",
                          "valid":true,
                          "pathInfo":[
                             "Group"
                          ],
                          "pathInfoIds":[
                             "GRP"
                          ],
                          "pathInfoTypes":[
                             "VIEW"
                          ],
                          "baseUuid":"201",
                          "children":[
                             {
                                "id":"12850",
                                "label":"Cal Yr 2019 - w/e 12/28/19",
                                "type":"GROUP_LEVEL_ITEM",
                                "valid":true,
                                "pathInfo":[
                                   "Characteristics",
                                   "Period Key"
                                ],
                                "pathInfoIds":[
                                   "GRP",
                                   "7944"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "GROUP"
                                ],
                                "baseUuid":"202",
                                "leaf":true
                             },
                             {
                                "id":"9376",
                                "label":"Cal Yr 2018 - w/e 12/29/18",
                                "type":"GROUP_LEVEL_ITEM",
                                "valid":true,
                                "pathInfo":[
                                   "Characteristics",
                                   "Period Key"
                                ],
                                "pathInfoIds":[
                                   "GRP",
                                   "7944"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "GROUP"
                                ],
                                "baseUuid":"202",
                                "leaf":true
                             },
                             {
                                "id":"9375",
                                "label":"Cal Yr 2017 - w/e 12/30/17",
                                "type":"GROUP_LEVEL_ITEM",
                                "valid":true,
                                "pathInfo":[
                                   "Characteristics",
                                   "Period Key"
                                ],
                                "pathInfoIds":[
                                   "GRP",
                                   "7944"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "GROUP"
                                ],
                                "baseUuid":"202",
                                "leaf":true
                             },
                             {
                                "id":"9374",
                                "label":"Cal Yr 2016 - w/e 12/31/16",
                                "type":"GROUP_LEVEL_ITEM",
                                "valid":true,
                                "pathInfo":[
                                   "Characteristics",
                                   "Period Key"
                                ],
                                "pathInfoIds":[
                                   "GRP",
                                   "7944"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "GROUP"
                                ],
                                "baseUuid":"202",
                                "leaf":true
                             }
                          ],
                          "leaf":false
                       }
                    ],
                    "leaf":false
                 }
              ],
              "accessType":"marketLevelReport"
           },
           {
              "id":"PRDC",
              "virtualDim":false,
              "hidden":false,
              "children":[
                 {
                    "id":"HRCH",
                    "label":"Hierarchy",
                    "type":"VIEW",
                    "valid":true,
                    "baseUuid":"300",
                    "children":[
                       {
                          "id":"2001",
                          "label":"Hierarchy 1",
                          "type":"HIERARCHY",
                          "valid":true,
                          "pathInfo":[
                             "Hierarchy"
                          ],
                          "pathInfoIds":[
                             "HRCH"
                          ],
                          "pathInfoTypes":[
                             "VIEW"
                          ],
                          "baseUuid":"301",
                          "children":[
                             {
                                "id":"150001",
                                "label":"Hierachy Level 1",
                                "type":"HIERARCHY_LEVEL",
                                "valid":true,
                                "pathInfo":[
                                   "Hierarchy",
                                   "Hierarchy 1"
                                ],
                                "pathInfoIds":[
                                   "HRCH",
                                   "2001"
                                ],
                                "pathInfoTypes":[
                                   "VIEW",
                                   "HIERARCHY"
                                ],
                                "baseUuid":"302",
                                "children":[
                                   {
                                      "id":"ALCOHOL",
                                      "label":"ALCOHOL",
                                      "type":"HIERARCHY_LEVEL_ITEM",
                                      "valid":true,
                                      "pathInfo":[
                                         "Hierarchy",
                                         "Hierarchy 1",
                                         "Hierarchy Level 1"
                                      ],
                                      "pathInfoIds":[
                                         "HRCH",
                                         "2001",
                                         "150001"
                                      ],
                                      "pathInfoTypes":[
                                         "VIEW",
                                         "HIERARCHY",
                                         "HIERARCHY_LEVEL"
                                      ],
                                      "baseUuid":"303",
                                      "leaf":true
                                   }
                                ],
                                "leaf":false
                             }
                          ],
                          "leaf":false
                       }
                    ],
                    "leaf":false
                 }
              ],
              "accessType":"marketLevelReport"
           },
           {
              "id":"FCT",
              "virtualDim":false,
              "hidden":false,
              "children":[
                 {
                    "id":"GRP",
                    "label":"Group",
                    "type":"VIEW",
                    "valid":true,
                    "baseUuid":"200",
                    "children":[
                       {
                          "id":"GRP",
                          "label":"Groups",
                          "type":"VIEW",
                          "valid":true,
                          "baseUuid":"400",
                          "children":[
                             {
                                "id":"9835",
                                "label":"Fact Groups",
                                "type":"GROUP",
                                "valid":true,
                                "pathInfo":[
                                   "Groups"
                                ],
                                "pathInfoIds":[
                                   "GRP"
                                ],
                                "pathInfoTypes":[
                                   "VIEW"
                                ],
                                "baseUuid":"401",
                                "children":[
                                   {
                                      "id":"10012",
                                      "label":"Sales Volume",
                                      "type":"GROUP_LEVEL",
                                      "valid":true,
                                      "pathInfo":[
                                         "Groups",
                                         "Fact Groups"
                                      ],
                                      "pathInfoIds":[
                                         "GRP",
                                         "9835"
                                      ],
                                      "pathInfoTypes":[
                                         "VIEW",
                                         "GROUP"
                                      ],
                                      "baseUuid":"402",
                                      "children":[
                                         {
                                            "id":"100128",
                                            "label":"Dollars",
                                            "type":"GROUP_LEVEL",
                                            "valid":true,
                                            "pathInfo":[
                                               "Groups",
                                               "Fact Groups",
                                               "Sales Volume"
                                            ],
                                            "pathInfoIds":[
                                               "GRP",
                                               "9835",
                                               "10012"
                                            ],
                                            "pathInfoTypes":[
                                               "VIEW",
                                               "GROUP",
                                               "GROUP_LEVEL"
                                            ],
                                            "baseUuid":"403",
                                            "children":[
                                               {
                                                  "id":"DOL",
                                                  "label":"$",
                                                  "type":"GROUP_LEVEL_ITEM",
                                                  "valid":true,
                                                  "pathInfo":[
                                                     "Groups",
                                                     "Fact Groups",
                                                     "Sales Volume",
                                                     "Dollars"
                                                  ],
                                                  "pathInfoIds":[
                                                     "GRP",
                                                     "9835",
                                                     "10012",
                                                     "100128"
                                                  ],
                                                  "pathInfoTypes":[
                                                     "VIEW",
                                                     "GROUP",
                                                     "GROUP_LEVEL",
                                                     "GROUP_LEVEL"
                                                  ],
                                                  "baseUuid":"404",
                                                  "leaf":true
                                               }
                                            ],
                                            "leaf":false
                                         }
                                      ],
                                      "leaf":false
                                   }
                                ],
                                "leaf":false
                             }
                          ],
                          "leaf":false
                       }
                    ],
                    "leaf":false
                 }
              ],
              "accessType":"marketLevelReport"
           }
        ]
     }
  },
  "timeMillis":0
}
